### ISSUE TITLE
make issues

### ISSUE THREAD

**Issue by Masber** [MDTEST-LANL/mdtest#6]
${MPI_CC} won't have any value so the command to compile won't work. In my case I get an error like:

t$ make
DLinux -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D__USE_LARGEFILE64=1 -D_HAS_S3 -I/usr/include/libxml2 -I/path/to/aws4c/include -L/path/to/aws4c/lib -laws4c_extra -laws4c -lcurl -lxml2 -g -o mdtest mdtest.c -lm
make: DLinux: Command not found
make: [mdtest] Error 127 (ignored)

**Comment by Masber** [comment]
sorry I just realised I didn't have aws4c was not installed

**Comment by aasraoui** [comment]
Hitting the same problem ..
@Masber  how did you install aws4c ?

Thanks!
