### ISSUE TITLE
mdtest not running on mpi

### ISSUE THREAD

**Issue by Masber** [MDTEST-LANL/mdtest#8]
Hi,

mdtest only runs on one remote host through mpi, my environment is openmpi on Centos6.7 and mdtest 1.9.3

These are the steps to reproduce the problem:

$ export MPI_CC=mpicc
$ make
mpicc -DLinux -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D__USE_LARGEFILE64=1  -g -o mdtest mdtest.c -lm
$ mpiexec --prefix /opt/openmpi -H omega-0-2 -np 1 ./mdtest -F -L -I 1 -z 0 -b 1 -d /directflow/RUNS/runs/test2/mdtest2/
-- started at 10/07/2016 18:28:46 --

mdtest-1.9.3 was launched with 1 total task(s) on 1 node(s)
Command line used: ./mdtest -F -L -I 1 -z 0 -b 1 -d /directflow/RUNS/runs/test2/mdtest2/
Path: /directflow/RUNS/runs/test2/mdtest2
FS: 54.6 TiB   Used FS: 79.9%   Inodes: 218.3 Mi   Used Inodes: 79.9%

1 tasks, 1 files

SUMMARY: (of 1 iterations)
   Operation                      Max            Min           Mean        Std Dev

---

   File creation     :         55.172         55.172         55.172          0.000
   File stat         :      19599.551      19599.551      19599.551          0.000
   File read         :      31300.776      31300.776      31300.776          0.000
   File removal      :       1821.235       1821.235       1821.235          0.000
   Tree creation     :        303.035        303.035        303.035          0.000
   Tree removal      :       1508.200       1508.200       1508.200          0.000

-- finished at 10/07/2016 18:28:46 --
$ mpiexec --prefix /opt/openmpi -H omega-0-3 -np 1 ./mdtest -F -L -I 1 -z 0 -b 1 -d /directflow/RUNS/runs/test2/mdtest2/
-- started at 10/07/2016 18:28:53 --

mdtest-1.9.3 was launched with 1 total task(s) on 1 node(s)
Command line used: ./mdtest -F -L -I 1 -z 0 -b 1 -d /directflow/RUNS/runs/test2/mdtest2/
Path: /directflow/RUNS/runs/test2/mdtest2
FS: 54.6 TiB   Used FS: 79.9%   Inodes: 218.3 Mi   Used Inodes: 79.9%

1 tasks, 1 files

SUMMARY: (of 1 iterations)
   Operation                      Max            Min           Mean        Std Dev

---

   File creation     :        301.944        301.944        301.944          0.000
   File stat         :      10512.040      10512.040      10512.040          0.000
   File read         :      20867.184      20867.184      20867.184          0.000
   File removal      :       1175.204       1175.204       1175.204          0.000
   Tree creation     :         80.295         80.295         80.295          0.000
   Tree removal      :       1358.699       1358.699       1358.699          0.000

-- finished at 10/07/2016 18:28:54 --
pwbcad@omega-0-1:mdtest$ mpiexec --prefix /opt/openmpi -H omega-0-2,omega-0-3 -np 1 ./mdtest -F -L -I 1 -z 0 -b 1 -d /directflow/RUNS/runs/test2/mdtest2/
-- started at 10/07/2016 18:29:03 --

mdtest-1.9.3 was launched with 1 total task(s) on 1 node(s)
Command line used: ./mdtest -F -L -I 1 -z 0 -b 1 -d /directflow/RUNS/runs/test2/mdtest2/
Path: /directflow/RUNS/runs/test2/mdtest2
FS: 54.6 TiB   Used FS: 79.9%   Inodes: 218.3 Mi   Used Inodes: 79.9%

1 tasks, 1 files

SUMMARY: (of 1 iterations)
   Operation                      Max            Min           Mean        Std Dev

---

   File creation     :         68.195         68.195         68.195          0.000
   File stat         :      13706.876      13706.876      13706.876          0.000
   File read         :      27060.026      27060.026      27060.026          0.000
   File removal      :       1680.410       1680.410       1680.410          0.000
   Tree creation     :         49.938         49.938         49.938          0.000
   Tree removal      :       1834.779       1834.779       1834.779          0.000

-- finished at 10/07/2016 18:29:03 --

As you can see on the last run, I tried to execute mdtest on 2 hosts. The output says "mdtest-1.9.3 was launched with 1 total task(s) on 1 node(s)" so it looks like it only ran on 1 of the nodes.

I'm wondering if mdtest needs to be compiles in a specific way in order to make it work with MPI?

thank you very much

**Comment by johnbent** [comment]
Are you sure mpiexec is not the problem. Can you show the output of running 'hostname' please to ensure that mpiexec is working correctly?

Thx

John

**Comment by Masber** [comment]
Hi John,

sorry I am not an MPI expert, I _think_ my MPI works fine. I followed this tutorial [http://mpitutorial.com/tutorials/mpi-hello-world/](tutorial) to test the configuration and it did work fine using same hosts (see below).

$ mpirun --prefix /opt/openmpi --host omega-0-1,omega-0-2,omega-0-3,omega-0-4 ./mpi_hello_world
Hello world from processor omega-0-2.local, rank 1 out of 4 processors
Hello world from processor omega-0-4.local, rank 3 out of 4 processors
Hello world from processor omega-0-3.local, rank 2 out of 4 processors
Hello world from processor omega-0-1.local, rank 0 out of 4 processors

Not sure if this is what you are after:

$ ssh omega-0-1 hostname
omega-0-1.local
$ ssh omega-0-2 hostname
omega-0-2.local
$ ssh omega-0-3 hostname
omega-0-3.local
$ ssh omega-0-4 hostname
omega-0-4.local
$ ssh omega-0-5 hostname
omega-0-5.local

Please let me know if need anything else

thank you very much

**Comment by Masber** [comment]
Hi John,

I just realised my problem was that I had to put more than 1 thread in order to make it work for multihost.

So I changed the command to:

mpiexec --prefix /opt/openmpi -host omega-0-9,omega-0-10 -np 2 ./mdtest -F -L -I 100 -z 0 -b 1 -d /directflow/RUNS/runs/test2/mdtest2/

I can see the job running on both hosts (see attached screenshot) however mdtest never finish.

![mdtest](https://cloud.githubusercontent.com/assets/722064/19225279/a7bc4708-8ee4-11e6-8b6e-01afb8b3df6d.PNG)

after a while I can see the message:

[omega-0-10.local][[40482,1],1][btl_tcp_frag.c:216:mca_btl_tcp_frag_recv] mca_btl_tcp_frag_recv: readv failed: Connection timed out (110)

thank you

**Comment by brettkettering** [comment]
Closing this issue.
